# Generated by Django 4.1 on 2022-10-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companylogo',
            options={'ordering': ('created',), 'verbose_name_plural': 'CompanyLogo'},
        ),
        migrations.AlterField(
            model_name='customerstories',
            name='company_picture_large',
            field=models.ImageField(blank=True, null=True, upload_to='Customerstories/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customerstories',
            name='company_picture_small',
            field=models.ImageField(blank=True, null=True, upload_to='Customerstories/%y/%m/%d'),
        ),
    ]
