# Generated by Django 4.1 on 2022-10-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_companylogo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstories',
            name='testimonal_subtitle',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
