# Generated by Django 4.1 on 2022-10-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_customerstories_testimonal_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstories',
            name='company_name',
        ),
        migrations.AddField(
            model_name='customerstories',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Customerstories/companylogo/%y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='CompanyLogo',
        ),
    ]
