# Generated by Django 4.1 on 2022-10-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0006_customerstories_status_customerstories_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstories',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish'),
        ),
    ]
