# Generated by Django 4.1 on 2022-11-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0008_remove_customerstories_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstories',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='created'),
        ),
    ]
