# Generated by Django 4.1 on 2022-11-10 12:22

from django.db import migrations, models
import testimonials.models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0009_alter_customerstories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstories',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Customerstories/companylogo/%y/%m/%d', validators=[testimonials.models.validate_file_extension]),
        ),
    ]
