# Generated by Django 4.1 on 2022-11-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0010_alter_customerstories_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstories',
            name='company_logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Customerstories/companylogo/%y/%m/%d'),
        ),
    ]
