# Generated by Django 4.1 on 2022-11-17 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonials', '0011_alter_customerstories_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo_img', models.ImageField(upload_to='Customerstories/blackquote/%y/%m/%d')),
                ('name', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
