# Generated by Django 4.1 on 2022-11-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0012_blockquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockquote',
            name='quote',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blockquote',
            name='company_logo_img',
            field=models.FileField(upload_to='Customerstories/blackquote/%y/%m/%d'),
        ),
    ]
