# Generated by Django 4.1 on 2023-02-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0014_remove_customerstories_company_picture_small_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstories',
            name='company_picture_description',
            field=models.CharField(default='Image Description', max_length=500),
        ),
    ]
