# Generated by Django 4.1 on 2022-10-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Posts'},
        ),
    ]
