# Generated by Django 4.1 on 2023-02-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishapp', '0004_alter_aboutauthor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='large_post_image',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_image_description',
            field=models.CharField(default='Image Description', max_length=500),
        ),
    ]
