# Generated by Django 4.1 on 2022-10-01 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=1000)),
                ('content1', tinymce.models.HTMLField()),
                ('title2', models.CharField(max_length=1000)),
                ('content2', tinymce.models.HTMLField()),
                ('title3', models.CharField(max_length=1000)),
                ('content3', tinymce.models.HTMLField()),
                ('title4', models.CharField(max_length=1000)),
                ('content4', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SecondSection',
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='SecondSection',
        ),
    ]
