# Generated by Django 4.1 on 2022-10-01 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0003_remove_thirdsection_pic_remove_thirdsection_pic_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fifthsection',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='author_pic',
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='author_title',
        ),
        migrations.RemoveField(
            model_name='fourthsection',
            name='subtitle_1',
        ),
        migrations.RemoveField(
            model_name='fourthsection',
            name='text_content',
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='leadername1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='leadername2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='leadername3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='leaderpic1',
            field=models.ImageField(null=True, upload_to='about_pic/leadership/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='leaderpic2',
            field=models.ImageField(null=True, upload_to='about_pic/leadership/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='leaderpic3',
            field=models.ImageField(null=True, upload_to='about_pic/leadership/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='leadertitle1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='leadertitle2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='leadertitle3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fourthsection',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='fourthsection',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thirdsection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
