# Generated by Django 4.1 on 2022-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_fifthsection_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdsection',
            name='heading',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
