# Generated by Django 4.1 on 2023-02-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_thirdsection_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThirdSection',
        ),
    ]
