# Generated by Django 4.1 on 2023-02-09 01:57

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_fifthsection_leaderpic1_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about_pic/icons/%y/%m/%d')),
                ('pic1_description', models.CharField(default='Image Description', max_length=500)),
                ('pic2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about_pic/icons/%y/%m/%d')),
                ('pic2_description', models.CharField(default='Image Description', max_length=500)),
                ('pic3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about_pic/icons/%y/%m/%d')),
                ('pic3_description', models.CharField(default='Image Description', max_length=500)),
                ('pic4', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about_pic/icons/%y/%m/%d')),
                ('pic4_description', models.CharField(default='Image Description', max_length=500)),
                ('pic5', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about_pic/icons/%y/%m/%d')),
                ('pic5_description', models.CharField(default='Image Description', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Aboutus icons',
                'ordering': ('-created',),
            },
        ),
    ]
