# Generated by Django 4.1 on 2023-02-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0008_aboutusicons'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusicons',
            name='pic6',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about_pic/icons/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='aboutusicons',
            name='pic6_description',
            field=models.CharField(default='Image Description', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutusicons',
            name='pic7',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about_pic/icons/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='aboutusicons',
            name='pic7_description',
            field=models.CharField(default='Image Description', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutusicons',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
