# Generated by Django 4.1 on 2023-02-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_aboutusicons_pic6_aboutusicons_pic6_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusicons',
            name='pic1_description',
            field=models.CharField(blank=True, default='Image Description', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusicons',
            name='pic2_description',
            field=models.CharField(blank=True, default='Image Description', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusicons',
            name='pic3_description',
            field=models.CharField(blank=True, default='Image Description', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusicons',
            name='pic4_description',
            field=models.CharField(blank=True, default='Image Description', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusicons',
            name='pic5_description',
            field=models.CharField(blank=True, default='Image Description', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusicons',
            name='pic6_description',
            field=models.CharField(blank=True, default='Image Description', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusicons',
            name='pic7_description',
            field=models.CharField(blank=True, default='Image Description', max_length=500, null=True),
        ),
    ]
