# Generated by Django 4.1 on 2023-02-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_firstsection_about_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstsection',
            name='about_text',
        ),
    ]
