# Generated by Django 4.1 on 2022-09-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'BillingQuestions',
            },
        ),
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=4000)),
            ],
            options={
                'verbose_name_plural': 'ContactFormModel',
            },
        ),
        migrations.CreateModel(
            name='OfficeAddressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_pic', models.ImageField(upload_to='office_pic/%y/%m/%d')),
                ('office_address', models.CharField(max_length=4000)),
            ],
            options={
                'verbose_name_plural': 'OfficeAddressDetails',
            },
        ),
        migrations.CreateModel(
            name='PreVisitInquires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'PreVisitInquires',
            },
        ),
        migrations.CreateModel(
            name='SalesQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'SalesQuestions',
            },
        ),
    ]
