# Generated by Django 4.1 on 2022-09-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingquestions',
            name='week_day',
            field=models.CharField(default='Mon-Fri', max_length=1000),
        ),
        migrations.AddField(
            model_name='previsitinquires',
            name='week_day',
            field=models.CharField(default='Mon-Fri', max_length=1000),
        ),
        migrations.AddField(
            model_name='salesquestions',
            name='week_day',
            field=models.CharField(default='Mon-Fri', max_length=1000),
        ),
    ]
