# Generated by Django 4.1 on 2022-09-30 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactus', '0003_billingquestions_user_previsitinquires_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeaddressdetail',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
