# Generated by Django 4.1 on 2022-09-30 17:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_officeaddressdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeaddressdetail',
            name='office_address',
            field=tinymce.models.HTMLField(),
        ),
    ]
