# Generated by Django 4.1 on 2022-09-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_alter_officeaddressdetail_office_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeaddressdetail',
            name='country_code',
            field=models.CharField(default='UK', max_length=100),
        ),
    ]
