# Generated by Django 4.1 on 2022-10-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0006_officeaddressdetail_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
