# Generated by Django 4.1 on 2023-02-08 09:15

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0008_alter_contactformmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeaddressdetail',
            name='office_pic_description',
            field=models.CharField(default='Image Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='officeaddressdetail',
            name='office_pic',
            field=imagekit.models.fields.ProcessedImageField(upload_to='office_pic/%y/%m/%d'),
        ),
    ]
