# Generated by Django 4.1 on 2022-08-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LizzyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_token', models.CharField(blank=True, max_length=1000, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('app_downloaded', models.BooleanField(default=False)),
                ('app_installed', models.BooleanField(default=False)),
                ('video_link', models.CharField(blank=True, default='', max_length=1000)),
                ('redirect_link', models.URLField(blank=True, default='')),
                ('link_visits', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'LizzyProfiles',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='NadiaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_token', models.CharField(blank=True, max_length=1000, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('app_downloaded', models.BooleanField(default=False)),
                ('app_installed', models.BooleanField(default=False)),
                ('video_link', models.CharField(blank=True, default='', max_length=1000)),
                ('redirect_link', models.URLField(blank=True, default='')),
                ('link_visits', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'NadiaProfiles',
                'ordering': ('-created',),
            },
        ),
    ]
