# Generated by Django 4.1 on 2022-08-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lizzyprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lizzyprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='nadiaprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='nadiaprofile',
            name='last_name',
        ),
    ]
