# Generated by Django 4.1 on 2022-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_lizzyprofile_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizzyprofile',
            name='installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nadiaprofile',
            name='installed',
            field=models.BooleanField(default=False),
        ),
    ]
