# Generated by Django 4.1 on 2022-09-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lizzyprofile_installed_nadiaprofile_installed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lizzyprofile',
            name='installed',
        ),
        migrations.RemoveField(
            model_name='nadiaprofile',
            name='installed',
        ),
    ]
