# Generated by Django 3.2.15 on 2022-09-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220909_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_exe_file', models.FileField(blank=True, upload_to='Downloads/mac/%y/%m/%d')),
                ('linux_exe_file', models.FileField(blank=True, upload_to='Downloads/linux/%y/%m/%d')),
                ('windows_exe_file', models.FileField(blank=True, upload_to='Downloads/windows/%y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
