# Generated by Django 3.2.15 on 2022-09-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizzyprofile',
            name='user_password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='nadiaprofile',
            name='user_password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
