# Generated by Django 4.1 on 2023-01-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
