# Generated by Django 4.1 on 2023-02-09 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadPageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('heading_description', models.CharField(max_length=2000)),
                ('second_heading', models.CharField(max_length=200)),
                ('second_heading_description', models.CharField(max_length=2000)),
                ('third_heading', models.CharField(max_length=200)),
                ('third_heading_description', models.CharField(max_length=2000)),
                ('fourth_heading', models.CharField(max_length=200)),
                ('fourth_heading_description', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Download Page Article',
                'ordering': ('-created',),
            },
        ),
    ]
