# Generated by Django 4.1 on 2023-02-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_application_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lizzyprofile',
            old_name='user_password',
            new_name='computer_password',
        ),
        migrations.RenameField(
            model_name='nadiaprofile',
            old_name='user_password',
            new_name='computer_password',
        ),
        migrations.RemoveField(
            model_name='lizzyprofile',
            name='linux_exe_file',
        ),
        migrations.RemoveField(
            model_name='lizzyprofile',
            name='mac_exe_file',
        ),
        migrations.RemoveField(
            model_name='lizzyprofile',
            name='windows_exe_file',
        ),
        migrations.RemoveField(
            model_name='nadiaprofile',
            name='linux_exe_file',
        ),
        migrations.RemoveField(
            model_name='nadiaprofile',
            name='mac_exe_file',
        ),
        migrations.RemoveField(
            model_name='nadiaprofile',
            name='windows_exe_file',
        ),
    ]
