# Generated by Django 4.1 on 2023-02-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_user_password_lizzyprofile_computer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizzyprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nadiaprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
