# Generated by Django 4.2 on 2023-07-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_kingpindrakoclients_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dll_file',
            field=models.FileField(blank=True, null=True, upload_to='Downloads/library/%y/%m/%d'),
        ),
    ]
