# Generated by Django 4.1 on 2022-10-31 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=2000)),
                ('subtitle', models.CharField(max_length=2000)),
                ('first_text', models.CharField(max_length=1000)),
                ('second_text', models.CharField(max_length=1000)),
                ('third_text', models.CharField(max_length=1000)),
                ('fourth_text', models.CharField(max_length=1000)),
                ('fifth_text', models.CharField(max_length=1000)),
                ('sixth_text', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ThirdColumn',
            },
        ),
        migrations.CreateModel(
            name='SixthColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('fullname', models.CharField(max_length=1000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='homepage/%y/%m/%d')),
                ('position_title', models.CharField(max_length=1000)),
                ('first_text', models.CharField(max_length=1000)),
                ('second_text', models.CharField(max_length=1000)),
                ('third_text', models.CharField(max_length=1000)),
                ('fourth_text', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SixthColumn',
            },
        ),
        migrations.CreateModel(
            name='SecondColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.CharField(max_length=2000)),
                ('second_text', models.CharField(max_length=2000)),
                ('third_text', models.CharField(max_length=2000)),
                ('fourth_text', models.CharField(max_length=2000)),
                ('fifth_text', models.CharField(max_length=2000)),
                ('sixth_text', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SecondColumn',
            },
        ),
        migrations.CreateModel(
            name='FourthColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.CharField(max_length=1000)),
                ('second_text', models.CharField(max_length=1000)),
                ('third_text', models.CharField(max_length=1000)),
                ('fourth_text', models.CharField(max_length=1000)),
                ('fifth_text', models.CharField(max_length=1000)),
                ('sixth_text', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FourthColumn',
            },
        ),
        migrations.CreateModel(
            name='FirstColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FirstColumn',
            },
        ),
        migrations.CreateModel(
            name='FifthColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=2000)),
                ('first_text', models.CharField(max_length=1000)),
                ('second_text', models.CharField(max_length=1000)),
                ('third_text', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FifthColumn',
            },
        ),
    ]
