# Generated by Django 4.1 on 2022-10-31 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sixthcolumn',
            old_name='position_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='secondcolumn',
            name='fifth_text',
        ),
        migrations.RemoveField(
            model_name='secondcolumn',
            name='sixth_text',
        ),
    ]
