# Generated by Django 4.1 on 2022-10-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_position_title_sixthcolumn_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sixthcolumn',
            name='first_text_subtitle',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sixthcolumn',
            name='fourth_text_subtitle',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sixthcolumn',
            name='second_text_subtitle',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sixthcolumn',
            name='third_text_subtitle',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
