# Generated by Django 4.1 on 2022-10-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_sixthcolumn_first_text_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sixthcolumn',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
