# Generated by Django 4.1 on 2022-11-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_sixthcolumn_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstColumn',
        ),
    ]
