# Generated by Django 4.1 on 2022-11-11 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('first_text', models.CharField(max_length=1000)),
                ('first_text_subtext', models.CharField(max_length=1000)),
                ('second_text', models.CharField(max_length=1000)),
                ('second_text_subtext', models.CharField(max_length=1000)),
                ('third_text', models.CharField(max_length=1000)),
                ('third_text_subtext', models.CharField(max_length=1000)),
                ('fourth_text', models.CharField(max_length=1000)),
                ('fourth_text_subtext', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SixthRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000)),
                ('application_deadline', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(max_length=1000)),
                ('employment_type', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('compensation', models.CharField(max_length=1000)),
                ('body', tinymce.models.HTMLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('first_text', models.CharField(max_length=1000)),
                ('first_text_subtitle', models.CharField(max_length=1000)),
                ('second_text', models.CharField(max_length=1000)),
                ('second_text_subtitle', models.CharField(max_length=1000)),
                ('third_text', models.CharField(max_length=1000)),
                ('third_text_subtitle', models.CharField(max_length=1000)),
                ('fourth_text', models.CharField(max_length=1000)),
                ('fourth_text_subtitle', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FourthRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('first_text', models.CharField(max_length=1000)),
                ('first_text_subtext', models.CharField(max_length=1000)),
                ('second_text', models.CharField(max_length=1000)),
                ('second_text_subtext', models.CharField(max_length=1000)),
                ('third_text', models.CharField(max_length=1000)),
                ('third_text_subtext', models.CharField(max_length=1000)),
                ('fourth_text', models.CharField(max_length=1000)),
                ('fourth_text_subtext', models.CharField(max_length=1000)),
                ('fifth_text', models.CharField(max_length=1000)),
                ('fifth_text_subtext', models.CharField(max_length=1000)),
                ('sixth_text', models.CharField(max_length=1000)),
                ('sixth_text_subtext', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirstRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.CharField(max_length=1000)),
                ('second_text', models.CharField(max_length=1000)),
                ('third_text', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FifthRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
