# Generated by Django 4.1 on 2022-11-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sixthrow',
            options={'ordering': ('-created',), 'verbose_name_plural': 'SixthRow'},
        ),
        migrations.AddField(
            model_name='sixthrow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sixthrow',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='created'),
        ),
        migrations.AddField(
            model_name='sixthrow',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
