# Generated by Django 4.1 on 2022-11-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created'),
        ),
        migrations.AlterField(
            model_name='myaccounts',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created'),
        ),
        migrations.AlterField(
            model_name='profileplan',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created'),
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created'),
        ),
        migrations.AlterField(
            model_name='support',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created'),
        ),
    ]
