# Generated by Django 4.1 on 2022-10-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingFAQ',
        ),
    ]
