# Generated by Django 4.1 on 2022-10-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_pricingfaq_answer_5_pricingfaq_answer_6_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightsection',
            options={'ordering': ('-created',), 'verbose_name_plural': 'HighLightSection'},
        ),
        migrations.AlterModelOptions(
            name='pricingcompareplan',
            options={'ordering': ('-created',), 'verbose_name_plural': 'PricingComparePlans'},
        ),
        migrations.AlterModelOptions(
            name='pricingfaq',
            options={'ordering': ('-created',), 'verbose_name_plural': 'PricingFAQs'},
        ),
        migrations.AlterModelOptions(
            name='professionalplan',
            options={'ordering': ('-created',), 'verbose_name_plural': 'ProfessionalPlan'},
        ),
        migrations.AlterModelOptions(
            name='teamsplan',
            options={'ordering': ('-created',), 'verbose_name_plural': 'TeamsPlan'},
        ),
    ]
