# Generated by Django 4.1 on 2022-11-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_highlightsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsplan',
            name='pricing',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
