# Generated by Django 4.1 on 2022-11-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_teamsplan_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalplan',
            name='pricing',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
